### PR TITLE
skip disabled native elements when serializing

### PR DESCRIPTION
**Pull request by danielandefors**

### CODE REVIEW

**Comment by danielandefors** [comment]
I signed it!

**Comment by danielandefors** [comment]
They were authored by me using an alternate email address in the commit.
This other email should be linked with my Google account.

**Comment by danielandefors** [comment]
Hi. 
For the sake of clarify, perhaps I should explain that this pull request is to align the functionality of the iron-form with that of a native html form. As you're probably aware of native forms will not submit disabled elements. Hence I think it would be nice if the iron-form's serialize method worked in similar fashion.

**Comment by notwaldorf** [comment]
Ah, awesome fix, thanks!

**Pull request merged**
